-- 公司Token
DROP TABLE IF EXISTS WEB_TOKEN_INFO;
CREATE TABLE WEB_TOKEN_INFO
(
  id          CHAR(36)       NOT NULL ,
  login_name  VARCHAR (255)  NOT NULL,
  login_channel TINYINT UNSIGNED NOT NULL DEFAULT 1,
  login_host VARCHAR (128)  NOT NULL ,
  login_datetime DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  last_visittime DATETIME   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  logout_datetime DATETIME   NULL DEFAULT NULL,
  expired_time TINYINT UNSIGNED NOT NULL DEFAULT 2,
  login_token  VARCHAR(512)  NOT NULL ,
  remark  VARCHAR(512)  NULL DEFAULT NULL,
  delete_flag TINYINT UNSIGNED NOT NULL DEFAULT 0,
  tenant_id   BIGINT(20)       NULL     DEFAULT 100000,
  creator     BIGINT(20)       NOT NULL DEFAULT -1,
  createTime  DATETIME         NOT NULL DEFAULT CURRENT_TIMESTAMP,
  editor      BIGINT(20)       NULL     DEFAULT NULL,
  editTime    DATETIME         NULL     DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
) DEFAULT CHARSET = utf8mb4
  COLLATE = 'utf8mb4_general_ci'
  ENGINE = InnoDB;

 ALTER TABLE WEB_TOKEN_INFO ADD FULLTEXT INDEX WEB_TOKEN_INFO_login_token_IDX  (login_token);


